
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smita
 */
public class IC9Frame extends javax.swing.JFrame {
// variables to create recipe string
    String displayRecipe=""; 
// Ingredients variable required to create recipe string    
    String crust="Crust: Regular<br>";
    String redSauce="";
    String pizzaCheese ="";
    String dicedOnion ="";
    String dicedGrnPpr ="";
    String pepperoni="";   
    String mushroom="";
    String jalapenos="";
    String sardines="";    
    String pineapple="";    
    String tofu=""; 
    String ham="";     
    String redpepper="";
    String drybasil="";   
// Instruction variable required to create recipe string    
    String icrust="Use a regular crust to make the base.<br>";
    String iredSauce="";
    String ipizzaCheese ="";
    String idicedOnion ="";
    String idicedGrnPpr ="";   
    String ipepperoni=""; 
    String imushroom="";
    String ijalapenos="";
    String isardines="";
    String ipineapple=""; 
    String itofu="";
    String iham="";
    String iredpepper="";
    String idrybasil="";     
    int totIngredient=1;
    int maxIngredient=8;
    
    /**
     * Creates new form IC9Frame
     */
    public IC9Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1_Crust_R = new javax.swing.JRadioButton();
        jRadioButton2_Crust_G = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizza");

        jLabel1.setText("Red Sauce 1/4 cup (1 - 2 times):");

        jLabel2.setText("Pizza Cheese 1/4 cup (1 - 2 times):");

        jLabel3.setText("Diced Onion 1/8 cup (1 - 2 times):");

        jLabel4.setText("Diced Green Pepper 1/8 cup (1 - 2 times):");

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jButton2.setText("Display");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Pizza Program by Smita Shinde");

        jRadioButton1_Crust_R.setSelected(true);
        jRadioButton1_Crust_R.setText("Regular");
        jRadioButton1_Crust_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1_Crust_RActionPerformed(evt);
            }
        });

        jRadioButton2_Crust_G.setText("Gluten Free");
        jRadioButton2_Crust_G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2_Crust_GActionPerformed(evt);
            }
        });

        jLabel6.setText("Crust :");

        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setText("Pepperoni 2 pieces ( 1 - 4 times):");

        jTextField5.setToolTipText("");
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });

        jLabel9.setText("Sliced mushroom 1/8 cup (1 - 2 times):");

        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });

        jLabel10.setText("Diced Jalapenos 1/8 cup (1 - 2 times):");

        jTextField7.setToolTipText("");
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });

        jLabel11.setText("Sardines 1 pieces ( 1 - 4 times):");

        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });

        jLabel12.setText("Pineapple Chunks 2 pieces ( 1 - 4 times):");

        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField9FocusLost(evt);
            }
        });

        jLabel13.setText("Tofu 1/4 cup (1 - 2 times):");
        jLabel13.setToolTipText("");

        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField10FocusLost(evt);
            }
        });

        jLabel14.setText("Ham Chunks 4 pieces ( 1 - 4 times):");

        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField11FocusLost(evt);
            }
        });

        jLabel15.setText("Dry Red Pepper Generous Sprinkle (1 - 4 times):");

        jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField12FocusLost(evt);
            }
        });

        jLabel16.setText("Dried basil Generous Sprinkle (1 - 2 times):");

        jTextField13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField13FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1_Crust_R)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2_Crust_G))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel16)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jTextField12)
                                    .addComponent(jTextField11)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField7)
                                    .addComponent(jTextField8)
                                    .addComponent(jTextField9)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton3, jButton4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1_Crust_R)
                    .addComponent(jRadioButton2_Crust_G)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField1, jTextField2, jTextField3, jTextField4, jTextField5});

        jEditorPane1.setEditable(false);
        jEditorPane1.setContentType("text/html"); // NOI18N
        jScrollPane2.setViewportView(jEditorPane1);

        jLabel7.setBackground(new java.awt.Color(51, 51, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Display Recipie in JEditorPane
        displayMsg();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // Reset all the test fields
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");  
        jTextField9.setText(""); 
        jTextField10.setText("");         
        jTextField11.setText("");         
        jTextField12.setText("");
        jTextField13.setText("");
        jEditorPane1.setText("");
        // set crust type to regular as default 
        jRadioButton1_Crust_R.setSelected(true);
        // unset crust type of Gluten free 
        jRadioButton2_Crust_G.setSelected(false);
        //reset receipe
        displayRecipe = "";
        //reset ingredients
        crust = "Crust : Regular<br>";
               
        redSauce = "";
        pizzaCheese = "";
        dicedOnion = "";
        dicedGrnPpr = "";
        pepperoni ="";
        mushroom="";
        jalapenos="";
        sardines="";
        pineapple="";
        tofu="";
        ham="";
        redpepper="";
        drybasil="";
        //reset instructions
        icrust = "Use a regular crust to make the base.<br>";
        iredSauce = "";
        ipizzaCheese = "";
        idicedOnion = "";
        idicedGrnPpr = "";
        ipepperoni ="";
        imushroom="";
        ijalapenos="";
        isardines="";
        ipineapple="";
        itofu="";
        iham="";
        iredpepper="";
        idrybasil="";
        // reset total ingredients
        totIngredient = 1;
        // reset the label heading
        jLabel7.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton1_Crust_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1_Crust_RActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1_Crust_R.isSelected()) {
            jRadioButton2_Crust_G.setSelected(false);
            icrust = "Use a regular crust to make the base.<br>";
            crust = "Crust : Regular<br>";
            displayMsg();
        }
    }//GEN-LAST:event_jRadioButton1_Crust_RActionPerformed

    private void jRadioButton2_Crust_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2_Crust_GActionPerformed
        // TODO add your handling code here:
        if (jRadioButton2_Crust_G.isSelected()) {
            jRadioButton1_Crust_R.setSelected(false);
            crust = "Crust : Gluten Free<br>";
            icrust = "Use a Gluten Free crust to make the base.<br>";
            displayMsg();
        }
    }//GEN-LAST:event_jRadioButton2_Crust_GActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            // Perform print function by invoking print dialogbox
            boolean prcomplete = jEditorPane1.print();
            if (prcomplete)
                JOptionPane.showMessageDialog(null,"Done printing", "Information", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(null,"Printing", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (PrinterException ex) {
            Logger.getLogger(IC9Frame.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        StringBuilder strbRedSauce=new StringBuilder("");
        //Check the Ingredient quantity with jTextField, Ingredient text, min quantity range, max quantity range, ingredient qty (using StringBuilder), measure(unit)
        checkIngredient(jTextField1,"Red Sauce",1,2,strbRedSauce,"1/4 cup");
        if (strbRedSauce.toString().equals("")) {
            // if empty string then reset the receipie ingredient quantity variables
            redSauce = ""; iredSauce = "";
        }
        else {
            // if non-emtpy string then set the receipie ingredient quantity variables
           redSauce = strbRedSauce.toString() + "<br>";
           iredSauce = ("Apply " + strbRedSauce.toString() + " over the crust spreading uniformly.<br>");
        }         
        // Calculate total ingredients using the updated ingredient quantities
        totIngredient = checkIngrNum("Red Sauce");
        displayMsg();
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        StringBuilder strbPizzaCheese =new StringBuilder("");
        checkIngredient(jTextField2,"Pizza Cheese",1,2,strbPizzaCheese,"1/4 cup");
        if (strbPizzaCheese.toString().equals("")) {
            pizzaCheese = ""; ipizzaCheese = "";
        }
        else {
           pizzaCheese = strbPizzaCheese.toString() + "<br>";
           ipizzaCheese = ("Spread " + strbPizzaCheese.toString() + " over the crust.<br>");
        }              
        totIngredient = checkIngrNum("Pizza Cheese");
        displayMsg();
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        StringBuilder strbDicedOnion =new StringBuilder("");        
        checkIngredient(jTextField3,"Diced Onion",1,2,strbDicedOnion,"1/8 cup");
        if (strbDicedOnion.toString().equals("")) {
            dicedOnion = ""; idicedOnion = "";
        }
        else {
           dicedOnion = strbDicedOnion.toString() + "<br>";
           idicedOnion = ("Add " + strbDicedOnion.toString() + " topping.<br>");
        }                         
        totIngredient = checkIngrNum("Diced Onion");
        displayMsg();
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
        StringBuilder strbDicedGrnPpr =new StringBuilder("");        
        checkIngredient(jTextField4,"Diced Green Pepper",1,2,strbDicedGrnPpr,"1/8 cup");
        if (strbDicedGrnPpr.toString().equals("")) {
            dicedGrnPpr = ""; idicedGrnPpr = "";
        }
        else {
           dicedGrnPpr = strbDicedGrnPpr.toString() + "<br>";
           idicedGrnPpr = ("Add " + strbDicedGrnPpr.toString() + " topping.<br>");
        }                 
        totIngredient = checkIngrNum("Diced Green Pepper");
        displayMsg();
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        StringBuilder strbPepperoni =new StringBuilder("");        
        checkIngredient(jTextField5,"Pepperoni",1,4,strbPepperoni,"2 pieces");
        if (strbPepperoni.toString().equals("")) {
            pepperoni = ""; ipepperoni = "";
        }
        else {
           pepperoni = strbPepperoni.toString() + "<br>";
           ipepperoni = ("Add " + strbPepperoni.toString() + " topping.<br>");
        }                
        totIngredient = checkIngrNum("Pepperoni");
        displayMsg();
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        // TODO add your handling code here:
       StringBuilder strbMushroom =new StringBuilder("");        
        checkIngredient(jTextField6,"Sliced Mushroom",1,2,strbMushroom,"1/8 cup");
        if (strbMushroom.toString().equals("")) {
            mushroom = ""; imushroom = "";
        }
        else {
           mushroom = strbMushroom.toString() + "<br>";
           imushroom = ("Add " + strbMushroom.toString() + " topping.<br>");
        }        
        totIngredient = checkIngrNum("Sliced Mushroom");
        displayMsg();  
    }//GEN-LAST:event_jTextField6FocusLost

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:
       StringBuilder strbJalapenos =new StringBuilder("");        
        checkIngredient(jTextField7,"Diced Jalapenos",1,2,strbJalapenos,"1/8 cup");
        if (strbJalapenos.toString().equals("")) {
            jalapenos = ""; ijalapenos = "";
        }
        else {
           jalapenos = strbJalapenos.toString() + "<br>";
           ijalapenos = ("Add " + strbJalapenos.toString() + " topping.<br>");
        }
        totIngredient = checkIngrNum("Diced Jalapenos");
        displayMsg();          
    }//GEN-LAST:event_jTextField7FocusLost

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
        // TODO add your handling code here:
       StringBuilder strbSardines =new StringBuilder("");        
        checkIngredient(jTextField8,"Sardines",1,4,strbSardines,"1 pieces");
        if (strbSardines.toString().equals("")) {
            sardines = ""; isardines = "";
        }
        else {
           sardines = strbSardines.toString() + "<br>";
           isardines = ("Add " + strbSardines.toString() + " topping.<br>");
        }
        totIngredient = checkIngrNum("Sardines");
        displayMsg();          
    }//GEN-LAST:event_jTextField8FocusLost

    private void jTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusLost
        // TODO add your handling code here:
       StringBuilder strbPineapple =new StringBuilder("");        
        checkIngredient(jTextField9,"Pineapple Chunks",1,4,strbPineapple,"2 pieces");
        if (strbPineapple.toString().equals("")) {
            pineapple = ""; ipineapple = "";
        }
        else {
           pineapple = strbPineapple.toString() + "<br>";
           ipineapple = ("Add " + strbPineapple.toString() + " topping.<br>");
        }
        totIngredient = checkIngrNum("Pineapple Chunks");
        displayMsg();          
    }//GEN-LAST:event_jTextField9FocusLost

    private void jTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusLost
        // TODO add your handling code here:
        StringBuilder strbTofu =new StringBuilder("");        
        checkIngredient(jTextField10,"Tofu",1,2,strbTofu,"1/4 cup");
        if (strbTofu.toString().equals("")) {
            tofu = ""; itofu = "";
        }
        else {
           tofu = strbTofu.toString() + "<br>";
           itofu = ("Add " + strbTofu.toString() + " topping.<br>");
        }
        totIngredient = checkIngrNum("Tofu");
        displayMsg();               
    }//GEN-LAST:event_jTextField10FocusLost

    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
        // TODO add your handling code here:
        StringBuilder strbHam =new StringBuilder("");        
        checkIngredient(jTextField11,"Ham Chunks",1,4,strbHam,"4 pieces");
        if (strbHam.toString().equals("")) {
            ham = ""; iham = "";
        }
        else {
           ham = strbHam.toString() + "<br>";
           iham = ("Add " + strbHam.toString() + " topping.<br>");
        }
        totIngredient = checkIngrNum("Ham Chunks");
        displayMsg();                       
    }//GEN-LAST:event_jTextField11FocusLost

    private void jTextField12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusLost
        // TODO add your handling code here
        StringBuilder strbRedpepper =new StringBuilder("");        
        checkIngredient(jTextField12,"Dry Red Pepper",1,4,strbRedpepper,"Generous sprinkle");
        if (strbRedpepper.toString().equals("")) {
            redpepper = ""; iredpepper = "";
        }
        else {
           redpepper = strbRedpepper.toString() + "<br>";
           iredpepper = ("Add " + strbRedpepper.toString() + " topping.<br>");
        }
        totIngredient = checkIngrNum("Dry Red Pepper");
        displayMsg();                       
    }//GEN-LAST:event_jTextField12FocusLost

    private void jTextField13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField13FocusLost
        // TODO add your handling code here:
        StringBuilder strbDrybasil =new StringBuilder("");        
        checkIngredient(jTextField13,"Dried Basil",1,2,strbDrybasil,"Generous sprinkle");
        if (strbDrybasil.toString().equals("")) {
            drybasil = ""; idrybasil = "";
        }
        else {
           drybasil = strbDrybasil.toString() + "<br>";
           idrybasil = ("Add " + strbDrybasil.toString() + " topping.<br>");
        }
        totIngredient = checkIngrNum("Dried Basil");
        displayMsg();         
    }//GEN-LAST:event_jTextField13FocusLost

        public void close() {
        // this will make sure WindowListener.windowClosing() et al. will be called.
        WindowEvent wev = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wev);

        // this will hide and dispose the frame, so that the application quits by
        // itself if there is nothing else around. 
        setVisible(false);
        dispose();
        // if you have other similar frames around, you should dispose them, too.

        // finally, call this to really exit. 
        // i/o libraries such as WiiRemoteJ need this. 
        // also, this is what swing does for JFrame.EXIT_ON_CLOSE
        System.exit(0); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IC9Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IC9Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IC9Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IC9Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IC9Frame().setVisible(true);
            }
        });
    }
    
    public boolean checkItem(Integer itemqty, String itemStr, int minqty, int maxqty) {
            if (itemqty < minqty || itemqty > maxqty ) {
                JOptionPane.showMessageDialog(null, "Quantity " + itemqty + " Out of Range.", itemStr, JOptionPane.INFORMATION_MESSAGE);
                return false;
            }
            else return true;

    }   
    public void checkIngredient(javax.swing.JTextField jIngredient, String StrIngredient, int minQty, int maxQty, StringBuilder strQty, String strUnit) {
        try {
            //parseInt to convert the textfield input to integer
            if (checkItem(Integer.parseInt(jIngredient.getText()),StrIngredient,minQty,maxQty)) {
                 strQty.append(StrIngredient + " ( " + strUnit + " ) " + jIngredient.getText() + " times " ) ;
            } else {
                //If number Quantity out of range then reset the Textfield  and ingredient variable quantity
                strQty.delete(0, strQty.length());
                strQty.append("");
                jIngredient.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid or Missing " + StrIngredient + 
                    " Quantity. Skipping " + StrIngredient + " and moving to next ingredient.\n" +
                    "To select " + StrIngredient + " please enter valid quantity in " + StrIngredient + " text field.", "Ingredients", WIDTH);
            strQty.delete(0, strQty.length());
            strQty.append("");
            jIngredient.setText("");
        } 
    }  
    
     public int checkIngrNum(String strIngreType) {
         // Calcuate the total ingredients
        int caclTotIngredient = 1 + (redSauce.equals("")?0:1) + (pizzaCheese.equals("")?0:1) +
                            (dicedOnion.equals("")?0:1) + (dicedGrnPpr.equals("")?0:1) +
                            (pepperoni.equals("")?0:1) + (mushroom.equals("")?0:1) +
                            (jalapenos.equals("")?0:1) + (sardines.equals("")?0:1) +
                            (pineapple.equals("")?0:1) + (tofu.equals("")?0:1) +
                            (ham.equals("")?0:1) + (redpepper.equals("")?0:1) + 
                            (drybasil.equals("")?0:1); 
        // check the total ingredients do not exeed the maximum ingredients
        if (caclTotIngredient > maxIngredient) {
            // if the total ingredients exeed the maximum ingredients display error message 
            JOptionPane.showMessageDialog(null, "Total Ingredient ( " + caclTotIngredient + ") more than " + maxIngredient +
                    " Enter number of indegredients less than maxIngredients ", strIngreType, JOptionPane.INFORMATION_MESSAGE);
            // reset the receipie and testfield value of the recent updated variable
            if (strIngreType.equals("Red Sauce")) {
                redSauce = "";
                iredSauce = "";
                jTextField1.setText("");}
            else if (strIngreType.equals("Pizza Cheese")) {
                pizzaCheese = "";
                ipizzaCheese = "";
                jTextField2.setText("");}
                if (strIngreType.equals("Diced Onion")) {
                dicedOnion = "";
                idicedOnion = "";
                jTextField3.setText("");}
            if (strIngreType.equals("Diced Green Pepper")) {
                dicedGrnPpr = "";
                idicedGrnPpr = "";
                jTextField4.setText("");}
            if (strIngreType.equals("Pepperoni")) {
                pepperoni = "";
                ipepperoni = "";
                jTextField5.setText("");}
            if (strIngreType.equals("Sliced Mushroom")) {
                mushroom = "";
                imushroom = "";
                jTextField6.setText("");}            
            if (strIngreType.equals("Diced Jalapenos")) {
                jalapenos = "";
                ijalapenos = "";
                jTextField7.setText("");}              
            if (strIngreType.equals("Sardines")) {
                sardines = "";
                isardines = "";
                jTextField8.setText("");}   
            if (strIngreType.equals("Pineapple Chunks")) {
                pineapple = "";
                ipineapple = "";
                jTextField9.setText("");}
            if (strIngreType.equals("Tofu")) {
                tofu = "";
                itofu = "";
                jTextField10.setText("");}            
            if (strIngreType.equals("Ham Chunks")) {
                ham = "";
                iham = "";
                jTextField11.setText("");} 
            if (strIngreType.equals("Dry Red Pepper")) {
                redpepper = "";
                iredpepper = "";
                jTextField12.setText("");}  
            if (strIngreType.equals("Dried Basil")) {
                drybasil = "";
                idrybasil = "";
                jTextField13.setText("");}  
        }
        // recalculate the total ingredients as the values are some ingredient might be updated during reset
        caclTotIngredient = 1 + (redSauce.equals("")?0:1) + (pizzaCheese.equals("")?0:1) +
                            (dicedOnion.equals("")?0:1) + (dicedGrnPpr.equals("")?0:1) +
                            (pepperoni.equals("")?0:1) + (mushroom.equals("")?0:1) +
                            (jalapenos.equals("")?0:1) + (sardines.equals("")?0:1) +
                            (pineapple.equals("")?0:1) + (tofu.equals("")?0:1)  +
                            (ham.equals("")?0:1) + (redpepper.equals("")?0:1) + 
                            (drybasil.equals("")?0:1);         
        return caclTotIngredient;
     }
        
    public void displayMsg() {                                         

        displayRecipe = "<h1><b><u>Pizza Receipie</u></b></h1>" +
                "<h2><b>Ingredients :</b></h2>" + crust + redSauce +
                pizzaCheese + dicedOnion + dicedGrnPpr + pepperoni + mushroom +
                jalapenos + sardines + pineapple + tofu + ham + redpepper + drybasil +
                "<h3>Total Number of Ingredients : " + totIngredient + "</h3><br>" +
                "<h2><b>Instructions :</b></h2>"  +
                icrust + iredSauce + ipizzaCheese +
                idicedOnion + idicedGrnPpr + ipepperoni + imushroom + 
                ijalapenos + isardines + ipineapple + itofu + iham + iredpepper + idrybasil +
                "Pre heat the oven to 450 degrees Fahrenhiet. " +
                "Pizza is to be appropriately cooked until crust is cooked and toppings are fully warmed. ";
        jEditorPane1.setText(displayRecipe);
        jLabel7.setText("<html>After all the ingredients with quantity are selected,<br>please select 'Print' button to print the final receipie.</html>");
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1_Crust_R;
    private javax.swing.JRadioButton jRadioButton2_Crust_G;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
